package es.finalPrimerCurso.finalPrimerCurso;

import javafx.fxml.FXML;

import java.io.File;
import java.io.IOException;
import java.util.Collections;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;

import es.finalPrimerCurso.finalPrimerCurso.Clases.Preguntas;
import javafx.event.ActionEvent;
import javafx.scene.control.Label;

public class PantallaFinalController {
	@FXML
	private Label textoFinal;
	private int vecesDescargado = 0;

	// Event Listener on Button.onAction
	@SuppressWarnings("exports")
	@FXML
	public void descargarPDF(ActionEvent event) {	
		PDDocument pdfFinal = new PDDocument();
		try {
		PDPage paginaUno = new PDPage(PDRectangle.A4);
		pdfFinal.addPage(paginaUno);
		PDPageContentStream contenidoPDF = new PDPageContentStream(pdfFinal, paginaUno);
		contenidoPDF.beginText();
		contenidoPDF.setFont(PDType1Font.TIMES_BOLD, 32);
		contenidoPDF.newLineAtOffset( 20, paginaUno.getMediaBox().getHeight() - 52);
		contenidoPDF.showText("¡Hola jugador!");
		contenidoPDF.endText();
		contenidoPDF.close();
		String rutaParaGuardarPDF = System.getProperty("user.home") + File.separator + "Desktop";
		if(vecesDescargado == 0) {
			pdfFinal.save(rutaParaGuardarPDF + File.separator + "preguntas.pdf");
			vecesDescargado++;
		}else {
			pdfFinal.save(rutaParaGuardarPDF + File.separator + "preguntas"+"("+vecesDescargado+")"+".pdf");
			vecesDescargado++;
		}
		}catch (IOException e) {
			e.printStackTrace();
		}finally {
			 if (pdfFinal != null) {
			        try {
			            pdfFinal.close();
			        }catch (IOException e) {
			            e.printStackTrace();
			        }
			 }
		}
	}

	// Event Listener on Button.onAction
	@FXML
	public void verGrafico(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button.onAction
	@FXML
	public void volverInicio(ActionEvent event) {
		try {
			PreguntasController.setAcierto(0);
			PreguntasController.setIndex(0);
			Collections.shuffle(Preguntas.getListaDePreguntas());
			App.setRoot("seleccionCantidadPreguntas");
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	// Event Listener on Button.onAction
	@FXML
	public void salirSimple(ActionEvent event) {
		System.exit(0);
	}
}
