package es.finalPrimerCurso.finalPrimerCurso;

import javafx.fxml.FXML;
import java.io.IOException;
import java.util.Collections;
/*
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
*/
import es.finalPrimerCurso.finalPrimerCurso.Clases.Preguntas;
import javafx.event.ActionEvent;
import javafx.scene.control.Label;



public class PantallaFinalController {
	@FXML
	private Label textoFinal;

	// Event Listener on Button.onAction
	@FXML
	public void descargarPDF(ActionEvent event) {	
		/*try {
			PDDocument pdfFinal = new PDDocument();
			PDPage paginaUno = new PDPage(PDRectangle.A4);
			pdfFinal.addPage(paginaUno);
			PDPageContentStream contenidoPDF = new PDPageContentStream(pdfFinal, paginaUno);
	           contenidoPDF.beginText();
	           //contenidoPDF.setFont(PDType1Font.TIMES_BOLD, 32);
	           contenidoPDF.newLineAtOffset( 20, paginaUno.getMediaBox().getHeight() - 52);
	           contenidoPDF.showText("Hello World!");
	           contenidoPDF.endText();
	           contenidoPDF.close();
	           pdfFinal.save("Preguntas.pdf");
		}catch (IOException e) {
			e.printStackTrace();
		}*/

	}
	// Event Listener on Button.onAction
	@FXML
	public void verGrafico(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void volverInicio(ActionEvent event) {
		try {
			PreguntasController.setAcierto(0);
			PreguntasController.setIndex(0);
			Collections.shuffle(Preguntas.getListaDePreguntas());
			App.setRoot("seleccionCantidadPreguntas");
		}catch (IOException e) {
			e.printStackTrace();
		}
	}
	// Event Listener on Button.onAction
	@FXML
	public void salirSimple(ActionEvent event) {
		System.exit(0);
	}
}
