package es.finalPrimerCurso.finalPrimerCurso;

import javafx.fxml.FXML;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.Collections;
import java.util.ResourceBundle;
import es.finalPrimerCurso.finalPrimerCurso.Clases.CrearEImprimirPDF;
import es.finalPrimerCurso.finalPrimerCurso.Clases.Preguntas;
import javafx.event.ActionEvent;
import javafx.scene.control.Alert;
import javafx.scene.control.Label;

public class PantallaFinalController {
	@FXML
	private Label textoFinal;
	private static int vecesDescargado = 0;
	
	
	

	public static int getVecesDescargado() {
		return vecesDescargado;
	}
	
	public static void aumentarVecesDescargado() {
		vecesDescargado++;
	}


	public void initialize(URL location, ResourceBundle resources) {
        textoFinal.setText("");
     
    }
    
    private void avisoDescargaPDF(ActionEvent event) {
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setHeaderText(null);
        alert.setTitle("Información de descarga");
        alert.setContentText("El archivo pdf se ha descargado correctamente en el escritorio");
        alert.showAndWait();
    }
	
	

	// Event Listener on Button.onAction
	@FXML
	public void descargarPDF(ActionEvent event) {
		CrearEImprimirPDF preguntasPDF = new CrearEImprimirPDF();
		avisoDescargaPDF(event);
	}

	// Event Listener on Button.onAction
	@FXML
	public void verGrafico(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button.onAction
	@FXML
	public void volverInicio(ActionEvent event) {
		try {
			PreguntasController.restablecerAciertos();
			PreguntasController.restablecerIndiceDePreguntas();
			Collections.shuffle(Preguntas.getListaDePreguntas());
			App.setRoot("seleccionCantidadPreguntas");
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	// Event Listener on Button.onAction
	@FXML
	public void salirSimple(ActionEvent event) {
		System.exit(0);
	}
}
